## 9 Numpy
Generate matrices A, with random Gaussian entries, B, a Toeplitz matrix, where A ∈ R^(n×m) and B ∈ R^(m×m),
for n = 200, m = 500.

### Exercise 9.1: Matrix operations
Calculate A + A, AA^T, A^TA and AB. Write a function that computes A(B − λI) for any λ.

In [2]:
import numpy as np
from scipy.linalg import toeplitz
A=np.random.normal(0,1,size=(200,500))


A.shape

(200, 500)

In [3]:
row=np.random.rand(500)
column=np.random.rand(500)
B=toeplitz(row,column)
B.shape


(500, 500)

In [4]:
result=np.zeros((200,500))
for i in range(len(A)):
    for j in range(len(A[0])):
        result[i][j] = A[i][j] + A[i][j]
result

array([[-1.00613257,  4.01183759,  1.90384166, ..., -0.58176554,
        -0.83737356, -2.23400773],
       [-4.13665174, -1.09446105, -2.81157175, ...,  0.96189824,
        -1.26639083, -0.27762361],
       [-3.47995541,  0.31044482, -1.98830445, ...,  0.13548437,
         0.05887074,  0.94254299],
       ...,
       [ 1.16484638, -3.45863761,  0.4152846 , ..., -3.7169924 ,
        -1.37547632,  0.58673368],
       [-0.93902192,  1.88993591,  0.23043242, ..., -1.87687942,
        -2.89039521,  1.15734057],
       [-2.2273894 , -1.17685894, -0.71454535, ...,  0.37185549,
        -2.87021328,  0.38213168]])

In [5]:
np.add(A,A)

array([[-1.00613257,  4.01183759,  1.90384166, ..., -0.58176554,
        -0.83737356, -2.23400773],
       [-4.13665174, -1.09446105, -2.81157175, ...,  0.96189824,
        -1.26639083, -0.27762361],
       [-3.47995541,  0.31044482, -1.98830445, ...,  0.13548437,
         0.05887074,  0.94254299],
       ...,
       [ 1.16484638, -3.45863761,  0.4152846 , ..., -3.7169924 ,
        -1.37547632,  0.58673368],
       [-0.93902192,  1.88993591,  0.23043242, ..., -1.87687942,
        -2.89039521,  1.15734057],
       [-2.2273894 , -1.17685894, -0.71454535, ...,  0.37185549,
        -2.87021328,  0.38213168]])

In [6]:
np.matmul(A,A.T)

array([[524.17015283,   6.03678287, -12.36357217, ..., -23.51909807,
        -25.23686548,  29.83387458],
       [  6.03678287, 499.27535363, -15.53043142, ..., -16.74301754,
         18.75246956,  -6.34229415],
       [-12.36357217, -15.53043142, 498.83530514, ...,  -9.32510432,
        -45.09827893, -16.70079028],
       ...,
       [-23.51909807, -16.74301754,  -9.32510432, ..., 418.4023397 ,
         -1.23114321, -31.90514892],
       [-25.23686548,  18.75246956, -45.09827893, ...,  -1.23114321,
        478.59772229,  -2.50813795],
       [ 29.83387458,  -6.34229415, -16.70079028, ..., -31.90514892,
         -2.50813795, 486.67462186]])

In [7]:
np.matmul(A,np.transpose(A))

array([[524.17015283,   6.03678287, -12.36357217, ..., -23.51909807,
        -25.23686548,  29.83387458],
       [  6.03678287, 499.27535363, -15.53043142, ..., -16.74301754,
         18.75246956,  -6.34229415],
       [-12.36357217, -15.53043142, 498.83530514, ...,  -9.32510432,
        -45.09827893, -16.70079028],
       ...,
       [-23.51909807, -16.74301754,  -9.32510432, ..., 418.4023397 ,
         -1.23114321, -31.90514892],
       [-25.23686548,  18.75246956, -45.09827893, ...,  -1.23114321,
        478.59772229,  -2.50813795],
       [ 29.83387458,  -6.34229415, -16.70079028, ..., -31.90514892,
         -2.50813795, 486.67462186]])

In [8]:
np.matmul(A.T,A)

array([[ 2.03797706e+02,  2.19173657e+01,  7.01733334e+01, ...,
         4.87728710e+00,  3.31115175e+00, -9.36254682e+00],
       [ 2.19173657e+01,  1.97678530e+02,  5.68933770e+00, ...,
        -1.60663378e-01,  7.59186586e+00, -1.07899869e+01],
       [ 7.01733334e+01,  5.68933770e+00,  1.98526880e+02, ...,
         1.01541899e+01,  8.58897139e+00, -1.10251840e+01],
       ...,
       [ 4.87728710e+00, -1.60663378e-01,  1.01541899e+01, ...,
         1.49758994e+02,  1.44750531e+01, -6.85726759e+00],
       [ 3.31115175e+00,  7.59186586e+00,  8.58897139e+00, ...,
         1.44750531e+01,  2.00853955e+02,  2.23803199e+01],
       [-9.36254682e+00, -1.07899869e+01, -1.10251840e+01, ...,
        -6.85726759e+00,  2.23803199e+01,  1.86593435e+02]])

In [9]:
np.matmul(A,B)

array([[ -4.74900735,   7.95181574,   2.00657779, ...,  14.29439114,
          0.33096145,  -2.26195053],
       [ 13.9531573 ,  18.00103121,   8.07230245, ...,  24.66231611,
         14.47592178,   6.40178875],
       [ -2.56779549,   7.56123039,   8.54743876, ...,   5.61145973,
        -10.14565867,   4.15371594],
       ...,
       [ -0.18107054,  -3.30633258,  -3.75164784, ...,   7.59324831,
          3.71146696,  -6.7255873 ],
       [  8.8896007 ,  21.25397645,   9.7417202 , ...,  21.8988886 ,
          9.90861594,  11.53925143],
       [-15.4099509 , -13.18005805, -13.39677536, ..., -13.3522657 ,
        -11.81698526, -30.22350263]])

In [10]:
import scipy.linalg as la
def funcEigen(A,B):
    C=np.identity(500)
    prod=np.matmul(la.eigvals(B),C)
    bmatrix=np.subtract(B,prod)
    result=np.matmul(A,bmatrix)
    return result
funcEigen(A,B)

array([[-1.14110337e+03  +0.j        , -4.62097011e+01 -27.21369713j,
        -5.21549390e+01 +27.21369713j, ...,
         8.19555199e+00  +0.53172154j, -5.69943382e+00  -0.59073154j,
        -8.29234580e+00  +0.59073154j],
       [-6.41938128e+03  +0.j        , -2.88627923e+02-154.06709385j,
        -2.98556652e+02+154.06709385j, ...,
        -9.86553283e+00  +3.01027796j, -1.96644403e+01  -3.344356j  ,
        -2.77385734e+01  +3.344356j  ],
       [-5.17645481e+02  +0.j        , -1.69886720e+01 -12.33520858j,
        -1.60024636e+01 +12.33520858j, ...,
         2.84702634e+00  +0.24101452j, -1.28790684e+01  -0.2677621j ,
         1.42030625e+00  +0.2677621j ],
       ...,
       [-4.82369399e+02  +0.j        , -2.62886451e+01 -11.54756607j,
        -2.67339604e+01 +11.54756607j, ...,
         5.00533283e+00  +0.22562497j,  1.15259422e+00  -0.25066463j,
        -9.28446004e+00  +0.25066463j],
       [-4.63196539e+03  +0.j        , -1.99940884e+02-111.14034999j,
        -2.11453140e+0

### Exercise 9.2: Solving a linear system
Generate a vector b with m entries and solve Bx = b.

In [11]:
def vectB(m):
    b=np.random.rand(m)
    return la.solve(B,b)
vectB(500)

array([-7.51644571e-01, -2.35711765e-01,  1.52241113e-01, -3.05092239e-01,
       -1.10302704e+00, -6.53643548e-02,  5.19859913e-02, -2.01576037e-01,
       -1.40294050e-01, -9.02946726e-02,  2.01346029e-01, -1.25532158e-01,
        4.19928275e-01, -2.93933205e-01, -4.61611998e-02,  5.02256513e-02,
       -4.00130157e-02, -2.22493708e-01, -3.66582134e-01, -4.02711478e-02,
        3.90385557e-02, -2.29256377e-01, -7.48110856e-02,  5.62923033e-02,
        3.57984368e-01, -6.84670779e-03, -2.29870027e-02, -1.21078427e-01,
       -2.92622224e-01, -5.05590048e-01,  4.45363985e-02,  3.48118924e-01,
       -1.02049760e-01, -4.02370911e-01,  3.58836246e-01,  3.52070660e-01,
        7.71380279e-02, -2.33896022e-01,  3.72454644e-01, -7.30612323e-03,
       -8.23236976e-02,  4.30896082e-02,  3.12965540e-01,  1.16592117e-01,
       -6.62652960e-02,  1.10096938e-01,  1.03142107e-01, -3.83586120e-01,
        2.48786173e-01,  2.77961957e-01, -6.88883162e-01, -3.11762568e-01,
        1.76446296e-01,  

### Exercise 9.3: Norms
Compute the Frobenius norm of A: ||A||F and the infinity norm of B: ||B||∞. Also find the largest and
smallest singular values of B.

In [12]:
la.norm(A,"fro")

314.93475955305166

In [13]:
la.norm(B,np.inf)

263.2031876701001

In [14]:
from scipy.sparse.linalg import svds
svds(B,which="LM")

(array([[-0.05339562, -0.06566133, -0.00434482,  0.06207201,  0.06410305,
         -0.04603459],
        [ 0.06227196, -0.06112144,  0.00744783, -0.00803165,  0.09247628,
         -0.04596611],
        [-0.05148039, -0.05428751,  0.01957079, -0.07783364,  0.05520498,
         -0.04593223],
        ...,
        [-0.00596502, -0.0471217 , -0.05490719,  0.01104584,  0.00828265,
         -0.04369876],
        [-0.02119731, -0.06440604, -0.04184104,  0.00731274,  0.01731568,
         -0.04375717],
        [ 0.04099213, -0.06686486, -0.02689309, -0.00652722,  0.01688051,
         -0.04383037]]),
 array([ 13.78244107,  13.91272952,  13.93381937,  14.26994045,
         14.30713847, 253.77175908]),
 array([[-0.04099213,  0.02119731,  0.00596502, ...,  0.05148039,
         -0.06227196,  0.05339562],
        [-0.06686486, -0.06440604, -0.0471217 , ..., -0.05428751,
         -0.06112144, -0.06566133],
        [ 0.02689309,  0.04184104,  0.05490719, ..., -0.01957079,
         -0.00744783,  0.004344

In [15]:
svds(B,which="SM")

(array([[ 0.07422828,  0.06774909,  0.05388559,  0.00944703,  0.00078037,
          0.04138759],
        [ 0.11722029,  0.05128339, -0.04421477,  0.01684989,  0.010686  ,
         -0.06032753],
        [ 0.07907501, -0.07937416, -0.05859166,  0.05921523, -0.02764583,
         -0.01933248],
        ...,
        [-0.01538186, -0.09754072, -0.0582741 , -0.13364873,  0.10861813,
          0.00049329],
        [-0.0489673 , -0.05227381,  0.10814506, -0.04575887,  0.0031773 ,
         -0.16127162],
        [-0.11669609,  0.07238764, -0.03218994,  0.0596206 , -0.06183554,
         -0.04517371]]),
 array([0.08110643, 0.1057912 , 0.11415224, 0.20331525, 0.27653264,
        0.28433774]),
 array([[ 0.11669609,  0.0489673 ,  0.01538186, ..., -0.07907501,
         -0.11722029, -0.07422828],
        [ 0.07238764, -0.05227381, -0.09754072, ..., -0.07937416,
          0.05128339,  0.06774909],
        [ 0.03218994, -0.10814506,  0.0582741 , ...,  0.05859166,
          0.04421477, -0.05388559],
       

In [16]:
la.norm(B,-2)

0.08110642895985057

In [17]:
la.norm(B,2)

253.77175908379888

### Exercise 9.4: Power iteration
Generate a matrix Z, n × n, with Gaussian entries, and use the power iteration to find the largest
eigenvalue and corresponding eigenvector of Z. How many iterations are needed till convergence?

Optional: use the time.clock() method to compare computation time when varying n.

In [33]:
Z=np.random.normal(0,1,size=(200,200))

### Exercise 9.6: Nearest neighbor
Write a function that takes a value z and an array A and finds the element in A that is closest to z. The
function should return the closest value, not index.

Hint: Use the built-in functionality of Numpy rather than writing code to find this value manually. In
particular, use brackets and argmin.

In [19]:
def nearestNeighbor(z, A):
    index = (np.abs(A - z)).argmin()
    return A[index]
A=np.random.randint(100,size=40)
print(A)
nearestNeighbor(80,A)

[ 4 82  8  9 40 20 48 85 90 81 82  8 87 64 68 30 81  8 77 78 50 59  6 82
 11 29 17 99 34 74 72 13 65 54 34 36 49 32 85  1]


81